### ISSUE TITLE
Player heads not dropping

### ISSUE THREAD

**Issue by kirbyy** [Royal-Rebels/Royal-Rebels#116]
japanda and hawk spent 45 minutes killing eachother and their heads would not drop. Not sure if this is just them having bad luck or the chance is too low?

**Comment by triarry** [comment]
Permissions, I forgot to set up permissions. I'll do that in a moment.

On Wed, Jun 3, 2015 at 2:34 PM, kirbyy <notifications@github.com> wrote:

> japanda and hawk spent 45 minutes killing eachother and their heads would
> not drop. Not sure if this is just them having bad luck or the chance is
> too low?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Royal-Rebels/Royal-Rebels/issues/116>.
>



-- 
*Nicholas Plante*
Bachelors Student | Computer Science
The College of Engineering
Drexel University 2016
nicholas.r.plante@drexel.edu

**Comment by triarry** [comment]
/pex reload and it'll be fixed. This closed #116.

On Wed, Jun 3, 2015 at 2:34 PM, Nick Plante <votus998@gmail.com> wrote:

> Permissions, I forgot to set up permissions. I'll do that in a moment.
>
> On Wed, Jun 3, 2015 at 2:34 PM, kirbyy <notifications@github.com> wrote:
>
>> japanda and hawk spent 45 minutes killing eachother and their heads would
>> not drop. Not sure if this is just them having bad luck or the chance is
>> too low?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Royal-Rebels/Royal-Rebels/issues/116>.
>>
>
>
>
> --
> *Nicholas Plante*
> Bachelors Student | Computer Science
> The College of Engineering
> Drexel University 2016
> nicholas.r.plante@drexel.edu
>



-- 
*Nicholas Plante*
Bachelors Student | Computer Science
The College of Engineering
Drexel University 2016
nicholas.r.plante@drexel.edu

**Comment by triarry** [comment]
Close #116
