### ISSUE TITLE
Problem with Nopvp settings

### ISSUE THREAD

**Issue by xConArtist** [Royal-Rebels/Royal-Rebels#124]
I have pvp disabled for myself.  When I'm in an unclaimed area i still take damage from mage spells. Also if the mage is outside a nopvp area they can attack even if I am in the nopvp zone.

**Comment by triarry** [comment]
I unfortunately think this will be unfixable. I will ask the plugin dev but I am not counting on it.

Best way to prevent this is to keep your zone pvp disabled. The PvP Toggle will protect from 66% of attacks, I know it is not ideal but we still have inventory protection on for if you do get killed by PvP.

I will keep this open until the dev responds. Sorry the response is not satisfactory.

**Comment by triarry** [comment]
Fixed by rules
