### ISSUE TITLE
Mythic Drops Dropping Stacked items

### ISSUE THREAD

**Issue by TheWillToThrill** [Royal-Rebels/Royal-Rebels#136]
Several times I got stacks of 3 of gold swords and other items that were in stacks of 3 while killing infernals

**Comment by kirbyy** [comment]
http://gyazo.com/d4a486c8629f1fea63437b32d62255a1
http://gyazo.com/d46e421d6496f222985882655aac7e0b

**Comment by triarry** [comment]
So is this mythicdrops or infernals

On Mon, Jun 8, 2015 at 2:59 AM, kirbyy <notifications@github.com> wrote:

> http://gyazo.com/d4a486c8629f1fea63437b32d62255a1
> http://gyazo.com/d46e421d6496f222985882655aac7e0b
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Royal-Rebels/Royal-Rebels/issues/136#issuecomment-109884315>
> .
>



-- 
*Nicholas Plante*
Bachelors Student | Computer Science
The College of Engineering
Drexel University 2016
nicholas.r.plante@drexel.edu
