### ISSUE TITLE
Items duplicating from PVP deaths

### ISSUE THREAD

**Issue by Bampires** [Royal-Rebels/Royal-Rebels#137]
I learned if you die from PVP, your items are duplicated, 
and players have asked me to duplicate my own items...
http://gyazo.com/5cdce3ff449d1d7c68c7200780c49c62

...and earlier in the night, i was watching players complaining that their items were dup'ed from PVP..
Definitely feel this should be looked into.

**Comment by triarry** [comment]
Thanks for letting me know! Will be resolved today.

**Comment by triarry** [comment]
Think it is confirmed the Archer plugin caused this. Try doing this now.
