### ISSUE TITLE
Not gaining levels from MCMMO?

### ISSUE THREAD

**Issue by Bampires** [Royal-Rebels/Royal-Rebels#146]
I'm unsure if this is a serverwide issue or if its just me but, I noticed, even though i've been using a bow & an axe for PVP/Mob Hunting, I'm not gaining levels for either..? It's only Axes/Archery/Unarmed/Swords (pvp related skills) that seem to be not working,

**Comment by triarry** [comment]
mcMMO combat levels are class-based.
If you're a knight, you get swords/axes.
If you're an archer, you get archery.
If you're a mage, you get unarmed.

I think you're an archer iirc, so you should be able to get archery no problem

**Comment by Bampires** [comment]
welllike. i havent been for archer so thats my problem ;o\
