### ISSUE TITLE
Charms not working

### ISSUE THREAD

**Issue by TheWillToThrill** [Royal-Rebels/Royal-Rebels#154]

**Comment by TheWillToThrill** [comment]
hobo and some other players have told me they are nonfunctional

**Comment by triarry** [comment]
Same. MythicDrops needs an update.

On Fri, Jun 26, 2015 at 5:12 PM, TheWillToThrill <notifications@github.com>
wrote:

> hobo and some other players have told me they are nonfunctional
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Royal-Rebels/Royal-Rebels/issues/154#issuecomment-115884467>
> .
>



-- 
*Nicholas Plante*
Bachelors Student | Computer Science
The College of Engineering
Drexel University 2016
nicholas.r.plante@drexel.edu
