### ISSUE TITLE
English skin for British Invasion

### ISSUE THREAD

**Issue by triarry** [Royal-Rebels/Royal-Rebels#17]
We need some skins for scouts, soldiers, and other British types in preparation for the British coming to the server.

**Comment by melliebean** [comment]
![](http://i.gyazo.com/8d8c55acf1ca9e10aea44412fc970fa7.png)

![](http://i.gyazo.com/c2d4a28e9ff9a6dca7fddb13088666c0.png)

**Comment by kirbyy** [comment]
Awesome stuff mellie :)

**Comment by triarry** [comment]
she stuffed em in my dropbox
