### ISSUE TITLE
Add more stuff to the store.

### ISSUE THREAD

**Issue by triarry** [Royal-Rebels/Royal-Rebels#183]

**Comment by Festivemadhomie** [comment]
Few ideas
Bottles of XP? 15 Per point?
Instant change of class?
Supporter pass?
Maybe another plot of Land in the Market?

**Comment by triarry** [comment]
bigger backpacks
yes on the xp
yes on the instant change
maybe on the pass
yes on the land

**Comment by triarry** [comment]
Done
