### ISSUE TITLE
Can't speak / or type commands 

### ISSUE THREAD

**Issue by 1AngelWolf** [Royal-Rebels/Royal-Rebels#193]
When I log on it says "[MV] - Sorry, you can't be in this world anymore!" And I do not have access to any command like /spawn or /home. I also cannot speak in Global.. xD so when people say wb I'm just silent and it seems like I'm being rude.. So basically I can't get home because I keep spawning at spawn when I log on and can't use /home.

**Comment by triarry** [comment]
Let me look into this right now.
