### ISSUE TITLE
Horses Bugs

### ISSUE THREAD

**Issue by NeighborLaBeouf** [Royal-Rebels/Royal-Rebels#251]
As a knight, I own a horse that I can summon with the command /h summon and banish with /h banish. Everytime I summon the horse and ride it and dismount, the horse is automatically claimed as mine. Once I banish it and resummon it, ride it, and dismount, the horse will automatically be claimed again. You can imagine this gets annoying once all of my allowed horse ownership slots are taken up by the same horse. Hopefully there is a way to disable automatic claiming or to count the horse being summoned as one entity instead of a new horse with the same name everytime.

Another issue I've had but not attempted replicating was giving the horse that can be summoned diamond horse armor. The horse was summoned missing its armor after being banished.

**Comment by triarry** [comment]
I will probably just have to either

1. Remove the mcmmo horse plugin and attempt to find another
2. Remove the banish command from the horse plugin, crippling cross-server knight horse mobility.
