### ISSUE TITLE
players can't break their own item frames after typing /unlock

### ISSUE THREAD

**Issue by triarry** [Royal-Rebels/Royal-Rebels#281]

**Comment by GameGuyComics** [comment]
I just noticed this issue minutes ago and created a GitHub account specifically for it. It would be really nice if this issue could be fixed soon. Thanks Triarry!

**Comment by triarry** [comment]
Hey GameGuy,

This is a known issue. The plugin updated to supposedly fix this issue, so its annoying its not fixed yet. I will give a look when I get home!

**Comment by GameGuyComics** [comment]
Alright. Thanks again Tri, it's really good to know that you're on top of this :)

**Comment by triarry** [comment]
Fixed! Type /unlock, right click the frame, and then left click the frame.
