### ISSUE TITLE
Tips on announcements

### ISSUE THREAD

**Issue by triarry** [Royal-Rebels/Royal-Rebels#284]

**Comment by triarry** [comment]
"make sure to do /sethome" when you find a place to live.
make sure to create warps to your favorite locations! /mw create warpname
you can delete warps you no longer need with /mw remove

**Comment by triarry** [comment]
Not rules - but definitely those 3 things, and more tips.

**Comment by Jappanda** [comment]
Keep Religious discussion to a minimum.
Remember that faction chats exist. /re for Rebels and /b for British

**Comment by TheWillToThrill** [comment]
Make sure to get your structures and land protected by asking a staff member in chat!

**Comment by MissSpooks** [comment]
No Caps spam

**Comment by NubTubz** [comment]
Find good a good location to settle or get to know the map using our dynmap! http://162.255.214.77:8123/

**Comment by triarry** [comment]
thanks!
