### ISSUE TITLE
Enderman Pet Issues

### ISSUE THREAD

**Issue by HotchkissOnFire** [Royal-Rebels/Royal-Rebels#287]
I have a pet Enderman, but my base isn't exactly Enderman-friendly. Meaning, the walls aren't all 3 blocks high. So whenever I walk into different rooms, my poor Blanco (his name) has to die and respawn every. single. time. The noises are very annoying... And its just downright horrible that he has to die for me to walk from one room into another!!! It says he despawns, but really he just teleports back to me. It also sounds off his death noise, so I was hoping maybe there was a way to just register it as him spawning back to me instead of him dying each time. 

- Listerine69

**Comment by triarry** [comment]
This isn't possible, sorry! This is why I recommend players get smaller pets. Sorry I didn't see this until now!
