### ISSUE TITLE
Log in to unrendered world, kicked shortly after

### ISSUE THREAD

**Issue by edlaurence** [Royal-Rebels/Royal-Rebels#312]
I seem to be unable to get the world to load. I see maybe a strip of land off in the distance while I fall through the world, then I'm kicked shortly after. Maybe this is why nobody is online on a Saturday evening?  :-)

Ed

**Comment by edlaurence** [comment]
![2015-11-14_17 11 12](https://cloud.githubusercontent.com/assets/12941287/11166647/e3b14eb2-8af2-11e5-96f0-3a1310087004.png)

**Comment by triarry** [comment]
Indeed. We are awaiting a response from our host. We tried what we could on
our side but it has not worked. Sorry Ed :(

**Comment by MissSpooks** [comment]
It seems to have gotten a whole lot better since then. Other than a few times where players were frequently kicked by an external host yesterday, it has been fine.

**Comment by triarry** [comment]
Good. We are still talking to the host to try to get it 100% resolved. We
are supremely sorry for what has been happening :( we thank you for working
hard during the downtime and everything should be fully resolved shortly!

**Comment by triarry** [comment]
host issues from November has not arisen. Closing.
