### ISSUE TITLE
Lag when Warping

### ISSUE THREAD

**Issue by MissSpooks** [Royal-Rebels/Royal-Rebels#317]
There seems to be an issue with players lagging when they warp. I hardly have this issue, but most others do.

**Comment by triarry** [comment]
When I'm on I do not get this issue. This may be an internet issue ... How many players are reporting this (approximately)

**Comment by MissSpooks** [comment]
Jap does, Hawkeye does, I get a little bit but not a whole lot. I could ask around with that.

**Comment by triarry** [comment]
This is simply attirbuted to server lag/home internet lag of the player, and cannot be fixed.
