### ISSUE TITLE
sword enchants for knights?

### ISSUE THREAD

**Issue by melliebean** [Royal-Rebels/Royal-Rebels#35]
http://www.spigotmc.org/resources/enchantment-upgrade.7193/
kurokit showed me this plugin - seems cool

**Comment by triarry** [comment]
I'm not super on board because I see this getting extremely overpowered

**Comment by KuroKit** [comment]
what about this one?
http://www.spigotmc.org/resources/enchantsplus.3396/
it could work for pretty much everyclass

**Comment by triarry** [comment]
Wow! That is super cool. I will look into this when I get home.

**Comment by triarry** [comment]
Done
