### ISSUE TITLE
Buff to leather armor for archers? Or iron?

### ISSUE THREAD

**Issue by triarry** [Royal-Rebels/Royal-Rebels#36]
Mages get double mana when they use leather armor of the same color.
Knights will soon be getting a diamond armor buff.
Should archers get the same treatment?

**Comment by KuroKit** [comment]
hmmm
archers should get chain if possible if not then iron

**Comment by triarry** [comment]
Chain. Good point maybe I'll do that so mages stay leather. Barbs could be
iron.

**Comment by triarry** [comment]
On hold because archers are overbuffed.

**Comment by triarry** [comment]
Nah.
