### ISSUE TITLE
hunger charm bug

### ISSUE THREAD

**Issue by de1012005** [Royal-Rebels/Royal-Rebels#370]
while having the hunger charm equipped on the tool belt i actually lost food instead of gaining i even took it off my tool belt put it in my inventory and back on my toolbelt and still lost food
![2016-01-20_00002](https://cloud.githubusercontent.com/assets/16806111/12464295/d8ce3080-bf8d-11e5-87f8-f3deeeb7c95e.jpg)

**Comment by triarry** [comment]
Confirmed by 3 people, will investigate

**Comment by triarry** [comment]
Fixed.
