### ISSUE TITLE
Name Doors in the Classroom are messed details below!

### ISSUE THREAD

**Issue by de1012005** [Royal-Rebels/Royal-Rebels#377]
when you try to join such and such clan it puts you in the wrong colony as in today crazyhorsemo attempted to join funtown and was put in KKS could be a bug or maybe they entered the wrong door im not sure

**Comment by triarry** [comment]
Which door did she try to walk through? I'll double check my logic - likely human error on my side :)

**Comment by triarry** [comment]
Yeah - if she went archer, it put a KKS as the prefix. Have her walk through again and she'll be fine.
