### ISSUE TITLE
dizzydon claims he lost his particle effects is no longer a donator

### ISSUE THREAD

**Issue by de1012005** [Royal-Rebels/Royal-Rebels#385]
as the title says he left one colony to join another and he immediately noticed he wasnt a donator anymore could be a possible bug idk

**Comment by triarry** [comment]
Hey, yeah. Currently a bug I haven't fixed yet. I'll come on after class
tonight and fix this....send me a pm thru steam please

**Comment by triarry** [comment]
fixed
