### ISSUE TITLE
Add animal farm limiter to help lag

### ISSUE THREAD

**Issue by triarry** [Royal-Rebels/Royal-Rebels#388]

**Comment by Bampires** [comment]
http://www.curse.com/bukkit-plugins/minecraft/chunkspawnerlimiter +  http://dev.bukkit.org/bukkit-plugins/clearlagg/

**Comment by de1012005** [comment]
https://www.spigotmc.org/resources/mob-farm-manager.15127/ uptodate also

**Comment by triarry** [comment]
Got it.
