### ISSUE TITLE
possible bug cannot seem to kill killer bunnies/take damage from minecarts

### ISSUE THREAD

**Issue by de1012005** [Royal-Rebels/Royal-Rebels#435]

**Comment by triarry** [comment]
Odd, will take a look at this. Might be a 1.9 bug.

**Comment by Bampires** [comment]
Killer bunnies can attack players and be killed.
Minecarts still unconfirmed.

**Comment by triarry** [comment]
Is the bug 'bunnies cannot take damage from minecarts', or 'anything cannot damage from minecarts'?

**Comment by de1012005** [comment]
no what it was i had a killer bunny in a minecart and it magically hopped out or fell out and when i went to attack it acted like it wasnt there but it was hopping around, and the minecart bc it was powered by redstone if you stand near it would hurt u bc u was being pushed by it
