### ISSUE TITLE
one person claimed they lost all there stuff due to a time-out in there house

### ISSUE THREAD

**Issue by de1012005** [Royal-Rebels/Royal-Rebels#459]
a videogamefire told me they lost all there stuff when they timed out of the game due to d/c or whichever. i did notice when i joined the server i was put in spawn i was still able to teleport to my house and other things.

**Comment by triarry** [comment]
Yeah we had some big issues last night. I will try to get on shortly and resolve this!

**Comment by triarry** [comment]
fixed
