### ISSUE TITLE
constant griefing using chickens

### ISSUE THREAD

**Issue by dizzydon** [Royal-Rebels/Royal-Rebels#468]
![2016-03-22_20 48 21](https://cloud.githubusercontent.com/assets/18018616/13972503/b3bb79b6-f06f-11e5-8e25-3425a8c41e07.png)
![2016-03-22_20 48 31](https://cloud.githubusercontent.com/assets/18018616/13972502/b3bb58c8-f06f-11e5-84d0-5679808ab2ba.png)
![2016-03-22_20 48 57](https://cloud.githubusercontent.com/assets/18018616/13972504/b61c7ec6-f06f-11e5-8a57-3c617e607c48.png)

every single time i log in to the server i have a massive amount of chickens across my plot in arch world. the person who keeps causing this is eatmagnificent and its just becoming a real hassle for me to come on and have to kill them every time i join in

**Comment by triarry** [comment]
I have mob spawning turned off in the other creative world, and I will be
sure to do it to this world as well. Sorry for the inconvenience! I never
got a reply on steam btw

On Tue, Mar 22, 2016 at 8:52 PM, dizzydon <notifications@github.com> wrote:

> [image: 2016-03-22_20 48 21]
> <https://cloud.githubusercontent.com/assets/18018616/13972503/b3bb79b6-f06f-11e5-8e25-3425a8c41e07.png>
> [image: 2016-03-22_20 48 31]
> <https://cloud.githubusercontent.com/assets/18018616/13972502/b3bb58c8-f06f-11e5-84d0-5679808ab2ba.png>
> [image: 2016-03-22_20 48 57]
> <https://cloud.githubusercontent.com/assets/18018616/13972504/b61c7ec6-f06f-11e5-8a57-3c617e607c48.png>
>
> every single time i log in to the server i have a massive amount of
> chickens across my plot in arch world. the person who keeps causing this is
> eatmagnificent and its just becoming a real hassle for me to come on and
> have to kill them every time i join in
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Royal-Rebels/Royal-Rebels/issues/468>
>



-- 
*Nicholas Plante*
Bachelors Student | Computer Science
The College of Engineering
Drexel University 2016
nicholas.r.plante@drexel.edu

**Comment by triarry** [comment]
fixefd
