### ISSUE TITLE
Eatmagnificent and the Chicken Incident

### ISSUE THREAD

**Issue by NoctOkami** [Royal-Rebels/Royal-Rebels#470]
There has been a bunch of times that I have been on, and Eatmagnificent has placed more and more chickens in Dizzydon architect area. This has happen multiple times. Both Diz and Bribum_ has kill hundreds of chickens. Yesterday, Bri cleared Diz's area of chickens and then, Eatmagnificent came on, talked for about 10-15 min, all while adding more chickens to Dizzydon's area again. I decided to take these screenshots. I did ask him not to, but he said no, and then said that he will continue to do it because Dizzydon did not say 'please', even though Diz has asked him multiple times to stop.

![2016-03-24_00 14 55](https://cloud.githubusercontent.com/assets/18044896/14009739/3fa0e8b2-f165-11e5-9987-5a512e892bab.png)
![2016-03-24_00 15 15](https://cloud.githubusercontent.com/assets/18044896/14009738/3fa0c814-f165-11e5-8475-58c253aef457.png)
![2016-03-24_00 22 28](https://cloud.githubusercontent.com/assets/18044896/14009737/3fa03304-f165-11e5-9b6f-9aba9b404cfd.png)
![2016-03-24_00 22 58](https://cloud.githubusercontent.com/assets/18044896/14009740/3fa1b54e-f165-11e5-9d97-f7fa808af68b.png)

**Comment by triarry** [comment]
I disabled mob spawning in the architect world this morning. I will deal
with eat magnificent tomorrow, but did this happen at all today?

**Comment by NoctOkami** [comment]
yes it did

**Comment by NoctOkami** [comment]
photos are all from the 23 of March

**Comment by triarry** [comment]
resolved
