### ISSUE TITLE
Wither Spawning

### ISSUE THREAD

**Issue by KuroKit** [Royal-Rebels/Royal-Rebels#54]
Need to turn off topside wither spawning because they get lose (as one has today) and drift to spawn and kill people

**Comment by triarry** [comment]
According to Andronicus, a wither was spawned a few thousand blocks away from spawn. Then it ended up over spawn, terrorizing players. So we need to make sure wither spawning is only enabled in the nether.

I should be able to do this by using permissions or mobcatcher config file.

**Comment by triarry** [comment]
Wither spawning is now only allowed in the nether.

**Comment by triarry** [comment]
When the end comes out, I will allow it there, too.
