### ISSUE TITLE
MythicMobs

### ISSUE THREAD

**Issue by triarry** [Royal-Rebels/Royal-Rebels#65]
Maybe this instead of infernals? Or even alongside?

http://dev.bukkit.org/bukkit-plugins/mythicmobs/

**Comment by KuroKit** [comment]
it seems interesting by wouldn't both be op? at least early in game?

**Comment by triarry** [comment]
They're customizable so not necessarily

**Comment by triarry** [comment]
On hold because OP

**Comment by triarry** [comment]
Done, replaced by Infernals.
