### ISSUE TITLE
DirtyArrows to replace CraftArrows

### ISSUE THREAD

**Issue by triarry** [Royal-Rebels/Royal-Rebels#66]
http://dev.bukkit.org/bukkit-plugins/dirtyarrows/

**Comment by KuroKit** [comment]
the only issue i see is that there are no recipes for the bows

**Comment by triarry** [comment]
You do it in an anvil but I can make it permission based for now

**Comment by KuroKit** [comment]
sounds good then!

**Comment by triarry** [comment]
Putting this on hold.

**Comment by triarry** [comment]
Done.
